### ISSUE TITLE
Promoting Kleetho will crash your client

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/BetterMinecraftChat#25]
Please go checkout kleetho over at www.twitch.tv/kleetho and don't forget to give them a follow geekH geekH 

java.lang.StringIndexOutOfBoundsException: String index out of range: 69
    at java.lang.String.substring(String.java:1950)
    at net.blay09.mods.bmc.handler.RenderHandler.onDrawChatMessagePost(RenderHandler.java:81)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_132_RenderHandler_onDrawChatMessagePost_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.blay09.mods.bmc.coremod.CoremodHelper.drawChatMessagePost(CoremodHelper.java:29)
    at net.minecraft.client.gui.GuiNewChat.func_146230_a(SourceFile:97)
    at net.minecraftforge.client.GuiIngameForge.renderChat(GuiIngameForge.java:804)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:197)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

serves her right

just kidding I love you kleeCuddle

**Comment by BlayTheNinth** [comment]
05:06
ZeekDaGeek: LONG STRING OF CHARACTER WITH EMOTES AT THE END LONG STRING OF CHARACTER WITH EMOTES AT THE END LONG STRING OF CHARACTER WITH EMOTES AT THE END AAAAAA geekH geekH
